server:
  port: 8084

spring:
  application:
    name: finflow-admin-service

  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: "*"